### ISSUE TITLE
Redmine 3.2 Error Not Found

### ISSUE THREAD

**Issue by adrianobr** [valexsantos/testit#1]
Redmine version: 3.2

I made the settings as recommendations, when I click on Add (test plan, test case etc.) is the error below.
![testit](https://cloud.githubusercontent.com/assets/7975205/15596028/5679e72a-239a-11e6-8c80-1995c831997b.PNG)

**Comment by valexsantos** [comment]
Can you attach the log file please? 

Thanks

**Comment by adrianobr** [comment]
Started GET "/projects/teste/testit/plans/new?modal=true" for 127.0.0.1 at 2016-05-27 21:35:39 +0530
Processing by TestitPlansController#new as _/_
  Parameters: {"modal"=>"true", "project_id"=>"teste"}
  Current user: admin (id=1)
  Rendered issues/_form_custom_fields.html.erb (7.9ms)
  Rendered plugins/testit/app/views/testit_common/_attributes.html.erb (77.4ms)
  Rendered plugins/redmine_workflow_enhancements/app/views/workflow_enhancements/_issue_popup.html.erb (0.8ms)
  Rendered plugins/redmine_agile/app/views/issues/_agile_data_fields.html.erb (29.6ms)
  Rendered plugins/testit/app/views/testit_common/_form.html.erb (127.0ms)
  Rendered plugins/testit/app/views/testit_plans/new.html.erb (129.5ms)
Missing template, responding with 404
  Rendered common/error.html.erb (0.3ms)
Completed 404 Not Found in 195ms (Views: 1.9ms | ActiveRecord: 32.2ms)

**Comment by adrianobr** [comment]
news?

**Comment by valexsantos** [comment]
I think this problem is caused by another plugin. So I'm removing the redmine hook calls from the plugin's views. I'm expecting  to push the fix later on today.
